name: bmi
dependencies:
    - python=3.5
    - numpy
    - pandas
    - jupyter
    - ipyparallel
    - notebook
    - seaborn
    - watermark
    - dask
    - theano
    - pip:
        - castra
        - graphviz
        - git+https://github.com/pymc-devs/pymc3.git#egg=pymc3